const menu = [
  {
    id: 1,
    title: 'Turmeric & Currant Rice',
    category: 'rice',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `Traditional to Indian cuisine, this side is a perfect match to rich Indian curries. The fragrant taste of turmeric and sweet bursts of currants work in harmony with the fluffy rice. Add this to our Butter Chicken, Indian vegetable Curry or Lamb Korma Curry  `,
  },
  {
    id: 2,
    title: 'Wonton Noodle Soup',
    category: 'noodle',
    price: 13.99,
    img: './images/item-2.jpeg',
    desc: `Thin egg noodles with homemade chicken dumplings, BBQ chicken, bean shoot, and broccoli served in homemade chicken stock topped with spring onion, coriander, and crunchy shallot.`,
  },
  {
    id: 3,
    title: 'Special Fried Rice',
    category: 'rice',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: `Fried rice with BBQ chicken, shrimp, egg, pea, carrot, bean shoot, and spring onion in oyster sauce.`,
  },
  {
    id: 4,
    title: 'Garlic Prawn Pizza',
    category: 'pizza',
    price: 20.99,
    img: './images/item-4.jpeg',
    desc: `Succulent prawns, garlic, diced tomato, green capsicum & mozzarella finished with aioli drizzle `,
  },
  {
    id: 5,
    title: 'Singapore Noodles',
    category: 'stir fry',
    price: 22.99,
    img: './images/item-5.jpeg',
    desc: `Thin rice noodles with BBQ chicken, shrimp, egg, onion, carrot, capsicum, and bean shoot stir fried in a mild curry sauce.`,
  },
  {
    id: 6,
    title: 'Seafood Noodle Soup',
    category: 'noodle',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: `Thin egg noodles with mixed seafood, bean shoot, broccoli, and mushroom served in homemade chicken stock topped with coriander, spring onion, and crunchy shallot.`,
  },
  {
    id: 7,
    title: 'berry nice parfait',
    category: 'desserts',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: `In a tall glass, with layers ofyoghurt, strawberry, granola, blueberry and granola. Top with extra fruit. Serve immediately `,
  },
  {
    id: 8,
    title: 'Vegan Brussel Sprout Tahini Pasta',
    category: 'vegan',
    price: 12.99,
    img: './images/item-8.jpeg',
    desc: `This Vegan Brussel Sprout  Tahini Pasta is so delicious, creamy, & full of flavor! With just 10 simple ingredients, you can make a creamy tahini sauce mixed with flavorful garlic & shaved brussels sprouts for a vegan pasta ready in 30 minutes or less!`,
  },
  {
    id: 9,
    title: 'Tomato Gnocchi Soup',
    category: 'vegan',
    price: 16.99,
    img: './images/item-9.jpeg',
    desc: `This Vegan Tomato Gnocchi Soup is packed with flavor, easy to make in one pot, and ready in just 30 minutes! Look no further for a truly cozy & comforting dairy-free soup.`,
  },
  {
    id: 10,
    title: 'Raspberry Smoothie',
    category: 'desserts',
    price: 8.99,
    img: './images/item-10.jpeg',
    desc: `Smoothie bowls are trending & it's no wonder when you see how brightly colored & flavorful they are. Try this delicious & healthy smoothie today!`,
  },
];
export default menu;
